print "<!DOCTYPE html>\n";
print "<html lang=\"vi\">\n";
print "\n";
print "<head>\n";
print "    <title>O-times</title>\n";
print "    <meta charset=\"utf-8\">\n";
print "    <link rel=\"icon\" href=\"../Picture/logo.png\">\n";
print "    <link rel=\"stylesheet\" type=\"text/css\" href=\"index.css\">\n";
print "    <link rel=\"stylesheet\" type=\"text/css\" href=\"../Fontawesome/css/fontawesome.min.css\">\n";
print "    <link rel=\"stylesheet\" type=\"text/css\" href=\"../Fontawesome/css/solid.css\">\n";
print "    <link rel=\"stylesheet\" type=\"text/css\" href=\"../Fontawesome/css/brands.min.css\">\n";
print "    <!-- <link rel=\"stylesheet\" href=\"http://use.fontawesome.com/releases/v5.1.0/css/all.css\" intergrity=\"sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt\" crossorigin=\"anomymous\"> -->\n";
print "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
print "    <link rel=\"stylesheet\" href=\"../Bootstrap/css/bootstrap.min.css\">\n";
print "    <link rel=\"stylesheet\" href=\"style.js\">\n";
print "</head>\n";
print "\n";
print "<body>\n";
print "\n";
print "    <div class=\"row banner\">\n";
print "        <div class=\"col-md-4 main_menu\">\n";
print "            <div class=\"sub-menu\">\n";
print "                <ul>\n";
print "                    <li> Trang chủ </li>\n";
print "                    <li>Đồng hồ nam\n";
print "                        <ul>\n";
print "                            <li><a href=\"hamlinton/hamlinton.html\">Hamlinton</a></li>\n";
print "                            <li><a href=\"casio/casionam/casionam.html\">Casio</a></li>\n";
print "                            <li><a href=\"seiko/Seiko.html\">Seiko</a></li>\n";
print "                        </ul>\n";
print "                    </li>\n";
print "                    <li>Đồng hồ nữ\n";
print "                        <ul>\n";
print "                            <li><a href=\"casio/casionu/casionu.html\">Casio</a></li>\n";
print "                        </ul>\n";
print "                    </li>\n";
print "\n";
print "                </ul>\n";
print "            </div>\n";
print "        </div>\n";
print "        <div class=\"col-md-5\">\n";
print "            <img src=\"../Picture/ten.png\">\n";
print "        </div>\n";
print "        <div class=\" col-md-3 \" style=\"padding-left: 100px;\">\n";
print "            <a href=\"dk-dn/dangnhap.html\"><i class=\"fas fa-users\"></i></a>\n";
print "            <a href=\"hoadon/trang1.html\"><i class=\"fas fa-shopping-cart\"></i></a>\n";
print "            <div class=\"timkiem\">\n";
print "                <input type=\"text\" name=\"search\" placeholder=\"Tìm kiếm\" id=\"value\">\n";
print "                <a href=\"timkiem/timkiem.html\"><button type=\"submit\"><i class=\"fas fa-search \"></i></button></a>\n";
print "            </div>\n";
print "        </div>\n";
print "    </div>\n";
print "    <div style=\"background-color: #e5e5e5\">\n";
print "        <div class=\"row hamlinton\">\n";
print "            <div class=\"col-md-6\">\n";
print "                <img class=\"anhhamlinton zoomanh\" src=\"../Picture/hamlinton/hamlinton.jpg\">\n";
print "                <a href=\"hamlinton/hamlinton.html\" class=\"nuthamlinton\">\n";
print "                    <button style=\"color: white;\" type=\"button\" class=\"btn btn-lg zoomanh\">Xem thêm</button>\n";
print "                </a>\n";
print "            </div>\n";
print "            <div class=\"col-md-6\">\n";
print "                <a href=\"hamlinton/H24655331_8.html\"\n";
print "                    style=\" text-decoration: none;position: relative ;top: 40px;left: 30px;\">\n";
print "                    <img class=\"H24655331_8 zoomanh\" src=\"../Picture/hamlinton/hamlintonnam/H24655331_8.png\">\n";
print "                    <div class=\"dongsp\">HAMLINTON AUTOMATIC</div>\n";
print "                    <div class=\"tensp\"><strong>VENTURA VENTURA XXL AUTO</strong></div>\n";
print "                    <div class=\"giasp\">20.348.500 VNĐ</div>\n";
print "                </a>\n";
print "            </div>\n";
print "        </div>\n";
print "\n";
print "        <div class=\"row anhcasio\">\n";
print "            <div id=\"carouselExampleIndicators\" class=\"carousel slide\" data-ride=\"carousel\">\n";
print "                <ol class=\"carousel-indicators\">\n";
print "                    <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"0\" class=\"active\"></li>\n";
print "                    <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"1\"></li>\n";
print "                    <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"2\"></li>\n";
print "                </ol>\n";
print "                <div class=\"carousel-inner\" style=\"height: 500px;\">\n";
print "                    <div class=\"carousel-item active\">\n";
print "                        <img src=\"../Picture/Casio/Satellite.jpg\" class=\"d-block w-100 zoomanh\">\n";
print "                    </div>\n";
print "                    <div class=\"carousel-item\">\n";
print "                        <img src=\"../Picture/Casio/gmw_b5000.jpg\" class=\"d-block w-100 zoomanh\">\n";
print "                    </div>\n";
print "                    <div class=\"carousel-item\">\n";
print "                        <img src=\"../Picture/Casio/Sheen.jpg\" class=\"d-block w-100 zoomanh\">\n";
print "                    </div>\n";
print "                </div>\n";
print "                <a class=\"carousel-control-prev\" href=\"#carouselExampleIndicators\" role=\"button\" data-slide=\"prev\">\n";
print "                    <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\n";
print "                    <span class=\"sr-only\">Previous</span>\n";
print "                </a>\n";
print "                <a class=\"carousel-control-next\" href=\"#carouselExampleIndicators\" role=\"button\" data-slide=\"next\">\n";
print "                    <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\n";
print "                    <span class=\"sr-only\">Next</span>\n";
print "                </a>\n";
print "            </div>\n";
print "        </div>\n";
print "        <div class=\"row seiko\">\n";
print "            <img src=\"../Picture/seiko/5s_bn01_global_26063041751206_jpg.jpg\" class=\"zoomanh\">\n";
print "            <a href=\"seiko/Seiko.html\" class=\"nutseiko\">\n";
print "                <button style=\"color: white;\" type=\"button\" class=\"btn btn-lg zoomanh\">Xem thêm</button>\n";
print "            </a>\n";
print "        </div>\n";
print "        <div class=\"loai\">\n";
print "            <div class=\"row ba\">\n";
print "                <div class=\"col-md-6\">\n";
print "                    <img class=\"anhdanhcau\"\n";
print "                        src=\"../Picture/Seiko/Astron_ND_WebSite-Banner_20190321_PC_18095433480648_jpg.jpg\">\n";
print "                    <a href=\"seiko/Seiko.html\" class=\"nam\">\n";
print "                        <button style=\"color: white;\" type=\"button\" class=\"btn btn-lg zoomanh\">Xem thêm</button>\n";
print "                    </a>\n";
print "                </div>\n";
print "                <div class=\"col-md-6\">\n";
print "                    <img src=\"../Picture/Casio/Sheen.jpg\">\n";
print "                    <a href=\"casio/casionu/she-4056pg-2a.html\" class=\"nu\">\n";
print "                        <button style=\"color: white;\" type=\"button\" class=\"btn btn-lg zoomanh\">Xem thêm</button>\n";
print "                    </a>\n";
print "                </div>\n";
print "            </div>\n";
print "        </div>\n";
print "    </div>\n";
print "    <div class=\"tail\">\n";
print "        <div class=\"row\">\n";
print "            <div class=\"col-md-4\" style=\"padding-top: 10px;\">\n";
print "                <p>\n";
print "                    <strong class=\"tuatail\">HỖ TRỢ</strong>\n";
print "                    <br>\n";
print "                    <a class=\"ndtail\" href=\"hotro/thanhtoan.html\">Hướng dẫn mua hàng</a>\n";
print "                    <br>\n";
print "                    <a class=\"ndtail\" href=\"hotro/doitra.html\">Chính sách đổi trả và bảo hành</a>\n";
print "                </p>\n";
print "                </p>\n";
print "            </div>\n";
print "            <div class=\"col-md-3\" style=\"padding-top: 10px;\">\n";
print "                <p>\n";
print "                    <strong class=\"tuatail\">LIÊN HỆ</strong>\n";
print "                    <br>\n";
print "                    <span class=\"ndtail\">\n";
print "                        SĐT:0908150900\n";
print "                        <br> Email:time79@gmail.com\n";
print "                        <br> Địa chỉ :79 Nguyễn Văn Luông quận 6\n";
print "                    </span>\n";
print "                </p>\n";
print "            </div>\n";
print "            <div class=\"col-md-2\">\n";
print "                <i class=\"fas fa-shipping-fast\"></i>\n";
print "                <p style=\"padding-top: 10px;\">Miễn phí vận chuyển </p>\n";
print "            </div>\n";
print "            <div class=\"col-md-3\">\n";
print "                <a href=\"#\"><i class=\"fab fa-facebook\"></i></a>\n";
print "                <a href=\"#\"><i class=\"fab fa-instagram\"></i></a>\n";
print "            </div>\n";
print "        </div>\n";
print "    </div>\n";
print "\n";
print "    <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\n";
print "    <script src=\"../../../Bootstrap/js/bootstrap.min.js\"></script>\n";
print "</body>\n";
print "\n";
print "</html>";
